ProyectoWeb/ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("servicios/", include("servicios.urls")),
    path("blog/", include("blog.urls")),
    path("contacto/", include("contacto.urls")),
    path("tienda/", include("tienda.urls")), 
    path("carro/", include("carro.urls")), 
    path("pedidos/", include("pedidos.urls")), 
    
    path("autenticacion/", include("autenticacion.urls")), 
    # path("ProyectoWebApp/", include("ProyectoWebApp.urls")),
    path("", include("ProyectoWebApp.urls")),
]

ProyectoWeb/blog/urls.py
from django.urls import path
from . import views


from django.conf import settings #importamos para que se vean las imagene s
from django.conf.urls.static import static # importamos para que se vean las imagenes


urlpatterns = [
    path('', views.blog, name="Blog"),
    # ahora vamos a filtrar por categoria 
    path('categoria/<int:categoria_id>/', views.categoria, name = 'categoria')
]

ProyectoWeb/carro/urls.py
from django.urls import path 

from . import views 
 
app_name = "carro"
 
urlpatterns = [
    path("agregar/<int:producto_id>/", views.agregar_producto, name = "agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name = "eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name = "restar"),
    path("limpiar/", views.limpiar_carro, name = "limpiar"),
]

ProyectoWeb/tienda/urls.py
from django.urls import path

from . import views



urlpatterns = [
    path('', views.tienda, name="Tienda"),
]

ProyectoWeb/tienda/models.py
from django.db import models

# Create your models here.
class CategoriaProd(models.Model):
    nombre = models.CharField(max_length = 50)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now_add = True)
    
    class Meta: 
        verbose_name = "categoriaProd"
        verbose_name_plural = "categoriasProd"
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length = 50)
    categorias = models.ForeignKey(CategoriaProd, on_delete = models.CASCADE)
    imagen = models.ImageField(upload_to = "tienda", null = True, blank = True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default = True )
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now_add = True)
    
    class Meta: 
        verbose_name = "producto"
        verbose_name_plural = "productos"
    
    def __str__(self): # no olvidar que es def
        return self.nombre

ProyectoWeb/carro/views.py
from django.shortcuts import render, redirect

from .carro import Carro
from tienda.models import Producto

# Create your views here.

# Creamos la vista para agregar productos al carro 
def agregar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id = producto_id)
    carro.agregar(producto = producto)

    # redireccinamos a la tienda
    return redirect("Tienda")

def eliminar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id = producto_id)
    carro.eliminar(producto = producto)

    # redireccinamos a la tienda
    return redirect("Tienda")

def restar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id = producto_id)
    carro.restar_producto(producto = producto)

    # redireccinamos a la tienda
    return redirect("Tienda")

def limpiar_carro(request, producto_id):
    carro = Carro(request)
    carro.limpiar_carro()
    # redireccinamos a la tienda
    return redirect("Tienda")

ProyectoWeb/tienda/views.py
from django.shortcuts import render
from .models import Producto, CategoriaProd


# Create your views here.
def tienda(request):
    productos = Producto.objects.all()
    return render(request, "tienda/tienda.html", {"productos": productos})

ProyectoWeb/tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>
        <tr>

            <th colspan = "3" class="text-center">
                Carro de compras
            </th>
        </tr>

        <tr>
            <th> Productos </th>
            <th> Cantidad </th>
            <th> Suma </th>
        </tr>
    </thead>
    
    <tbody>
        {% comment %} Si se han agregado articulos al carro entonces que se pongan esos articulos en el carro  {% endcomment %}
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td> {{ value.nombre }} </td>
                    <td> {{ value.cantidad }} </td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}"  class="btn btn-sm btn-success"> + </a>
                        <a href="{% url 'carro:restar' value.producto_id %}"  class="btn btn-sm btn-success"> - </a>
                        <br/>

                        {{ value.precio }} $
                    </td>
                </tr>

            {% endfor %} 
        
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </td>
            </tr>


        {% endif %}
    </tbody>    

    <tfoot>
        <tr>
            <td colspan="3"> Total: {{ importe_total_carro }}  </td>
        </tr>
        
        {% if request.session.carro.items %}
        <tr>
            <td colspan="3" style="text-align: center;">
                <a href="../pedidos" class="btn btn-success"> Add pedido </a>
            </td>
        </tr>
        {% endif %}

    </tfoot>

</table>